##This is a workflow to demonstrate self hosted runner job processing

name: 'self hosted runner demo'

on: 
  workflow_dispatch:
  push:

jobs:
  hello-self-hosted-runner:
    runs-on: [self-hosted, Linux, x64, gpu, production]
    steps:
    - name: run-me-inside-self-hosted-runner
      run: echo "Howdy Github Actions. i know I am getting executed inside self hosted runner"

    - name: sleep for 100 seconds
      run: sleep 100
